making tests pass in ci

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -18,6 +18,12 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.event.pull_request.head.ref }}
+      - name: Check for .env file
+        run: |
+          if [ -f ".env" ]; then
+            echo "Error: .env file is present!"
+            exit 1
+          fi
       - name: Install uv
         uses: astral-sh/setup-uv@v5
       - name: Install the project
