test: testing scaffolding (#13)

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -18,6 +18,12 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.event.pull_request.head.ref }}
+      - name: Check for .env file
+        run: |
+          if [ -f ".env" ]; then
+            echo "Error: .env file is present!"
+            exit 1
+          fi
       - name: Install uv
         uses: astral-sh/setup-uv@v5
       - name: Install the project
@@ -39,10 +45,6 @@ jobs:
       - name: fail if readme changed and we aren't on PR
         uses: nickcharlton/diff-check@main
         if: github.event_name != 'pull_request'
-#      - name: Test with pytest
-#        run: |
-#          uv run python -m pytest  --cov-report xml:pytest.xml --cov=bw_dedup
-#        uses: MishaKav/pytest-coverage-comment@main
-#        with:
-#          pytest-coverage-path: ./pytest-coverage.txt
-#          junitxml-path: ./pytest.xml
+      - name: Test with pytest
+        run: |
+          uv run python -m pytest .
